# Custom Language File for Launcher Customizer

[ejs.app]
title = "Rise of Shinobi Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "https://twitter.com/riseshinobi"
mediaInstagramURL = "https://www.instagram.com/rise.of.shinobi"
mediaYouTubeURL = "https://www.youtube.com/@riseofshinobi"
mediaDiscordURL = "https://discord.gg/w9AYxup"

[ejs.settings]
sourceGithubLink = "https://discord.gg/w9AYxup"
supportLink = "https://discord.gg/w9AYxup"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Rise of Shinobi !"
welcomeDescription = ""
welcomeDescCTA = "Tu n'es qu'à quelques clics du monde Shinobi"
